### ISSUE TITLE
Delete links

### ISSUE THREAD

**Issue by timohzbs** [DecaTec/sharerenamer#11]
Hey,

how can I delete used links?
deleted a link and now I cant use the same name again for a new folder. 
thx

**Comment by DecaTec** [comment]
Hi,
did you simply delete the shared link or did you delete the file/folder which was shared by link?
If a shared file/folder is deleted, it gets moved to the trah bin. The shared link is still there, but inactive. If you would restore the file/folder, the shared link would be active again. So in order to reuse a custom link, delete the file/folder, empty the trash bin and wait for the next tick of the cron job. Then you should be able to use the same custom link again.

**Comment by timohzbs** [comment]
Thank you very much.
This helped 👍🏼

Mit freundlichen Grüßen

Timo
Mail: TClemens@live.com<mailto:TClemens@live.com>


Diese E-Mail wurde von meinem iPhone gesendet.


Am 14.02.2019 um 07:47 schrieb DecaTec <notifications@github.com<mailto:notifications@github.com>>:


Hi,
did you simply delete the shared link or did you delete the file/folder which was shared by link?
If a shared file/folder is deleted, it gets moved to the trah bin. The shared link is still there, but inactive. If you would restore the file/folder, the shared link would be active again. So in order to reuse a custom link, delete the file/folder, empty the trash bin and wait for the next tick of the cron job. Then you should be able to use the same custom link again.

**Comment by DecaTec** [comment]
OK, I will close the issue then.
