### ISSUE TITLE
Using sharerenamer in NextCloud Mobile App

### ISSUE THREAD

**Issue by SurajVerma** [DecaTec/sharerenamer#13]
Hi,
No doubt it is a very useful app, thank you for that. 👍:sparkles:
Is there a way to use this in NextCloud Mobile App ? I installed it today on my NextCloud server. On browser, I am getting the option to rename shared link but in NC Android App, if I click share, it doen't give me any option to rename the link.

**Comment by DecaTec** [comment]
The Nextcloud app only adds this functionality to the web UI of NC.
I'm not an Android app dev, but afaik this functionality had to be implemented in the Android app directly.

Maybe @AndyScherzinger can give some more details.

**Comment by SurajVerma** [comment]
I was under the impression that NextCloud app is just a wrapper for the web version.

**Comment by DecaTec** [comment]
Not exactly. I was only involved in the development of the NC app for Windows (Mobile) and there it wasn't a wrapper around the web UI. 
I think this is also true for the other mobile apps (Android/iOS).

**Comment by AndyScherzinger** [comment]
The mobile apps are all native except for some features like the login or editing files within Collabora. Except for some features the client offers the features based on the simple server installation and doesn't many server side features brought in via plug ins because than the client would depend on plugins for it to work which is too risky for the long term.

You can of course raise such a feature request on the Android App tracker and see what other developers think.

**Comment by DecaTec** [comment]
@AndyScherzinger Thanks for the clarification!
Would this be a feature which has to be implemented in the Android app only, or does the NC app require some modification in order to be recognized by the Android app?

**Comment by AndyScherzinger** [comment]
Can't really say to be honest. Maybe @tobiasKaminsky knows.

**Comment by tobiasKaminsky** [comment]
> Would this be a feature which has to be implemented in the Android app only, or does the NC app require some modification in order to be recognized by the Android app?

The server app needs to expose it via capability, so that client app can check for it and enable the corresponding action.
As @AndyScherzinger said we focus on features in server that are available to all…
So I would vote to support this if it as an integrated part of the server.

**Comment by DecaTec** [comment]
@tobiasKaminsky There was some discussion about integrating this app into NC directly, but this was denied, because in bigger instances, the links would collide as they are per instance and not per user.

@SurajVerma So I'll close this issue. If you want to see it integrated in the mobile apps, please open an issue in the corresponding repos. If this feature will be integrated, I'll do my best to support integration in the mobile apps.

**Comment by SurajVerma** [comment]
:+1:  :smile:
