### ISSUE TITLE
Flag as incompatible with NC 18+

### ISSUE THREAD

**Issue by Windyo** [DecaTec/sharerenamer#27]
App should be flagged as incompatible with NC18+ seeing as it doesn't work there as referenced in #21.
Currently it's an available app to download with no warning message re: deprecation of function.

**Comment by DecaTec** [comment]
In the `info.xml`, it's marked as compatible from NC 14 to NC 17.
That it is still available in the app store (even in NC 18/19) is due to the strategy, Nextcloud shows incompatible apps. It's marked as "untested" with the hint that it may not work properly with your current NC version.
<img width="833" alt="grafik" src="https://user-images.githubusercontent.com/9428899/85288899-d59aaf80-b496-11ea-8a0e-50a9e5fa70c6.png">

If this behavior is not what you expected, please feel free to open an issue in the Nextcloud repo that they should mark incompatible apps in a different manner.

**Comment by Windyo** [comment]
Weird, for me it shows it as fully valid :
![image](https://user-images.githubusercontent.com/17938171/85289306-c14eb680-b486-11ea-86ba-a2b2e3a8d2e4.png)
that's actually why I opened this issue, I wouldn't have if it did in fact flag it as "untested".

I do see it flagged if I open the full store page, though...
Probably something on my instance, i'll see wtf is happening on my side. Issue closed

**Comment by ifuchs** [comment]
It shows as valid (or at least it is not flagged) but it does not work in (my instance) of NC 18 when installed from the App list.

**Comment by ifuchs** [comment]
Is that version 2.7.3?

**Comment by DecaTec** [comment]
Yes, 2.7.3

**Comment by Windyo** [comment]
yeah agreed with ifuchs, I see it as valid absolutely everywhere...
![image](https://user-images.githubusercontent.com/17938171/85292547-987cf000-b48b-11ea-906f-2bcd90a5ef1e.png)

Added a longer screenshot to showcase that other apps are in fact flagged as incompatible.

Inspecting the app after reinstalling does show
`<nextcloud min-version="14" max-version="17" />`

So I'm confused. I'll open a thread on the Nextcloud store page to see what's happening.

**Comment by nursoda** [comment]
Most probably you _once_ enabled the untested app, maybe in a much earlier (NC) version. Upon update or even uninstallation, that flag is not reset. It resides in config.php. It's easy to delete there, just delete the corresponding line. If you can't access that file directly due to hosting restrictions, OCCweb might be a way to do it. Not sure how though. Here's how it looks:
```
  'app_install_overwrite' => 
  array (
    0 => 'sharerenamer',
  ),
```

**Comment by Windyo** [comment]
that was it. Congrats, closing linked issue as well :)
