### ISSUE TITLE
Not working in NextCloud 14

### ISSUE THREAD

**Issue by jcklpe** [DecaTec/sharerenamer#7]
Is this going to be updated for 14? Just wanted to check.

**Comment by jcklpe** [comment]
@DecaTec Weird, it's working now. Maybe I just had to uninstall and reinstall. Thanks!

**Comment by DecaTec** [comment]
Yes, sometimes there were problems when updating Nextcloud 13 to 14. In these cases, the app was shown as not compatible to NC 14 and you simply had to re-install it.
I think this could be caused by a lot files changed from v1.x.x (for NC <= 13) and v2.x.x (for NC >= 14).

However, glad that your problem is solved now.
