### ISSUE TITLE
Unable to set the same name of an archive we delete

### ISSUE THREAD

**Issue by castillo92** [DecaTec/sharerenamer#9]
Steps to follow to produce the problem:

1. Create some file, for example file_1.txt"
2. Share the file and change the name of the URL, for example "test1"
        2.1.- We can try if it's working.... https://myserver.com/s/test1 ....... YES
3. Delete the file "file_1.txt"
        3.1.- We can try if it's working.... https://myserver.com/s/test1 ....... NO, of course, we delete the file.
5. Create other new file, for example "file_2.txt"
6. Share the file and change the name of the URL to "test1" again.

Problem: The web page notice that this name it's in use.

Suggestion of improvement:
A little box asking to overwrite the share link or overwrite directly

**Comment by DecaTec** [comment]
This is by design.
A shared link is kind of a property of a file or folder. If you delete a file/folder, it's still there - in the trash bin. When the file is restored from the trash, the shared link will work again.

In order to re-use a shared link name, delete the file, empty the trash bin and wait for the next tick of the cron job.

As shared links are per instance and not per user, it wouldn't be a great idea to allow overriding shared links.
